
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get Current Version from pom.xml
      id: get_version
      run: echo "BASE_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout | cut -d'.' -f1-2)" >> $GITHUB_ENV

    - name: Generate Patch Version
      id: patch_version
      run: echo "PATCH_VERSION=${{ env.BASE_VERSION }}.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Update Maven Version
      run: mvn versions:set -DnewVersion=${{ env.PATCH_VERSION }}

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Rename JAR with Version
      run: |
        JAR_NAME=$(ls target/*.jar | grep -v "original" | head -n 1)
        mv $JAR_NAME target/myapp-${{ env.PATCH_VERSION }}.jar

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ env.PATCH_VERSION }}.jar
        path: target/myapp-${{ env.PATCH_VERSION }}.jar
