
name: Java CI with Maven

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Maven Version Bump Action
      uses: nnichols/maven-version-bump-action@v5
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: myapp-${{ env.NEW_VERSION }}.jar
        path: target/myapp-${{ env.NEW_VERSION }}.jar
